---
- name: disable swap space
  command: swapoff -a

- name: confirm there is no swap
  file:
    path: /swapfile
    state: absent
    
- name: copy kubernetes.repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644
  become: yes

- name: update
  yum:
    name: '*'
    state: present
  become: yes

- name: install cooooooberneties
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ yumbo }}"
  become: yes

- name: start and enable cooooooooooberneties
  systemd:
    name: kubelet
    state: started
    enabled: yes
  become: yes

- name: mkdir
  file:
    path: /tmp/helm
    state: directory
- name: download helm
  get_url:
    url: https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
    dest: /tmp/helm/helm.tar.gz
- name: untar
  unarchive: 
    src: /tmp/helm/helm.tar.gz
    dest: /tmp/helm/
    remote_src: yes
- name: copy
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/bin
    mode: 0755
    remote_src: yes
- name: clean up
  file:
    path: /tmp/helm/
    state: absent
