---
- name: disable swap space
  command: swapoff -a

- name: confirm there is no swap
  file:
    path: /swapfile
    state: absent
    
- name: copy kubernetes.repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644
  become: yes

- name: update
  yum:
    name: '*'
    state: present
  become: yes

- name: install cooooooberneties
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ yumbo }}"
  become: yes

- name: start and enable cooooooooooberneties
  systemd:
    name: kubelet
    state: started
    enabled: yes
  become: yes